markdown: rdiscount
pygments: true
permalink: /:categories/:title
rdiscount:
  extensions: [smart]

name: UCSD Stingray
url: http://e4e.ucsd.edu
description: Mr. Ray Sting
twitter: UCSDNGS
github: UCSD-E4E
gravatar_url: http://www.stingrayauv.com/uploads/6/7/1/9/6719262/6189977_orig.png?1324976069
